### ISSUE TITLE
Simple case is needed

### ISSUE THREAD

**Issue by cwjwudi** [kmontreal-hub/MySQL-Connector-#1]
Very good work! Can you give a simple B&R PLC based program showing how to call this library?

**Comment by kmontreal-hub** [comment]
Thanks! My project file is too big for github, but here is a link to an example on dropbox.

https://www.dropbox.com/scl/fi/qyapv27llknmfv8r33je0/SQL-Connector-Example.zip?rlkey=oup9n4xjb1u6x5qf4tshcgosl&st=odo7a45u&dl=0

Basically you have 1 task operate the connection and other tasks send queries to it that return an array of strings. Once you get the return data you just need to parse it into whatever datatype you want. In this example I'm getting a machine list from a database and parsing it into a complex datatype. I also have a task where I'm doing an insert into the database, you need to build the string from code and send it to the mysql task.

**Comment by cwjwudi** [comment]
Thank you very much for your kind help! I need to use MySQL with the B&R controller recently. I can't wait to try the library!

**Comment by cwjwudi** [comment]
Hi, I tried to compile and run the case you gave. I tried to connect to a local database using the local emulation and I seem to have some problems as shown below, error 32651 is reported. this seems to be a TCP connection problem, do you have any suggestions?
![Snipaste_2024-09-19_23-01-44](https://github.com/user-attachments/assets/e29b3d2a-b4cb-47f9-9299-73a8c4fa0876)
![Snipaste_2024-09-19_22-59-08](https://github.com/user-attachments/assets/448c6b33-0af1-48a8-a33b-efd00a5e2ff1)
![Snipaste_2024-09-19_22-58-04](https://github.com/user-attachments/assets/00368492-aa39-40aa-baed-82fba72ac950)

**Comment by kmontreal-hub** [comment]
You'll notice theres a task names ip_config in the project, in the main cyclic for the task I'm running code to automatically change the IP address for IF3, so you want to either remove that section of code and set the IP manaually or modify the code to set your IP address to 127.0.0.1

When I ran the example I gave, I was using a PC2200 and had IF3 (ETH1) connected to a remote PC running the database on a different IP address, so I'm not certain this will fix your issue. 

Let me know how it works out!

![image](https://github.com/user-attachments/assets/50f77b7a-7d48-4806-adb6-e69ecf8cc9fe)

![image](https://github.com/user-attachments/assets/ff17919d-2cf5-4455-8252-1d7d30e50229)

**Comment by kmontreal-hub** [comment]
I just tried with ArSim and changing the IP address of IF3 to 127.0.0.1 and it doesn't appear to work. Do you have physical hardware that you can try on? I only use ArSim on rare occasions, usually I am using a physical PLC and a PC running a MySQL Database for my applications.

My guess for the error is that because IF3 isn't bound to actual hardware that it can't assign the IP address.

**Comment by cwjwudi** [comment]
Thank you. I try your library in real PLC X20CP1584, it works!
